[DocUpdate] Add jax installation on TPU VM step to mlperf instruction
Reason:
MLperf instruction is missing the step of install jaxon cloud TPU VM.
Without that, starting server will fail with the following

```
Attempting to initialize the jax distributed system...
DEBUG:2025-02-15 04:00:44,925:jax._src.clusters.cloud_tpu_cluster:181: Did not detect cloud TPU VM
DEBUG:jax._src.clusters.cloud_tpu_cluster:Did not detect cloud TPU VM
2025-02-15 04:00:44,925 - jax._src.clusters.cloud_tpu_cluster - DEBUG - Did not detect cloud TPU VM
DEBUG:2025-02-15 04:00:44,925:jax._src.clusters.cloud_tpu_cluster:216: Did not detect cloud TPU VM
DEBUG:jax._src.clusters.cloud_tpu_cluster:Did not detect cloud TPU VM
2025-02-15 04:00:44,925 - jax._src.clusters.cloud_tpu_cluster - DEBUG - Did not detect cloud TPU VM
DEBUG:2025-02-15 04:00:44,925:jax._src.clusters.cluster:86: Could not find a known environment for initializing distributed JAX. Known environments: OmpiCluster, SlurmCluster, Mpi4py
Cluster, BaseTpuCluster, GceTpuCluster, GkeTpuCluster, K8sCluster
DEBUG:jax._src.clusters.cluster:Could not find a known environment for initializing distributed JAX. Known environments: OmpiCluster, SlurmCluster, Mpi4pyCluster, BaseTpuCluster, Gce
TpuCluster, GkeTpuCluster, K8sCluster
2025-02-15 04:00:44,925 - jax._src.clusters.cluster - DEBUG - Could not find a known environment for initializing distributed JAX. Known environments: OmpiCluster, SlurmCluster, Mpi4
pyCluster, BaseTpuCluster, GceTpuCluster, GkeTpuCluster, K8sCluster
Traceback (most recent call last):
  File "/mnt/github/maxtext/MaxText/maxengine_server.py", line 66, in <module>
    pyconfig.initialize(sys.argv)
  File "/mnt/github/maxtext/MaxText/pyconfig.py", line 849, in initialize
    _config = _HyperParameters(argv, **kwargs)
  File "/mnt/github/maxtext/MaxText/pyconfig.py", line 368, in __init__
    max_utils.maybe_initialize_jax_distributed_system(raw_keys)
  File "/mnt/github/maxtext/MaxText/max_utils.py", line 278, in maybe_initialize_jax_distributed_system
    jax.distributed.initialize(initialization_timeout=raw_keys["jax_distributed_initialization_timeout"])
  File "/mnt/venv/jetstream/lib/python3.10/site-packages/jax/_src/distributed.py", line 262, in initialize
    global_state.initialize(coordinator_address, num_processes, process_id,
  File "/mnt/venv/jetstream/lib/python3.10/site-packages/jax/_src/distributed.py", line 79, in initialize
    raise ValueError('coordinator_address should be defined.')
ValueError: coordinator_address should be defined.
```