[TestCleanup] Clean up test_server.py (#186)
* Change from assert to self.assert
* Change unittest.IsolatedAsyncioTestCase to TestCase to run
  tests synchronously and sequentially to avoid following warning
  (which seems to be due to underlying grpc issue that is still open
  https://github.com/grpc/grpc/issues/25364)

```
BlockingIOError: [Errno 35] Resource temporarily unavailable
```